databases:
  - name: miplanilla-db
    databaseName: miplanilla
    plan: free

services:
  - type: web
    name: miplanilla
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: MiPlanilla
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:l/gLoagjGlz7C1WvT9Wzmmiw08AtA71hMsO3jF/DTAY=
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: es
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: miplanilla-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: miplanilla-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: miplanilla-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: miplanilla-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: miplanilla-db
          property: password
