<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'; import CrudModal from '@/Components/CrudModal.vue';
import {Head,Link,router,useForm} from '@inertiajs/vue3'; import {computed,ref,watch} from 'vue';
const props=defineProps({empresas:Array,periodos:Array,resumen:Object,periodoSeleccionado:Object});
const meses=['','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']; const hoy=new Date();
const empresaFiltro=ref(props.periodoSeleccionado?.empresa_id||''),estadoFiltro=ref(''),periodoId=ref(props.periodoSeleccionado?.id||'');
const periodosFiltrados=computed(()=>props.periodos.filter(p=>(!empresaFiltro.value||String(p.empresa_id)===String(empresaFiltro.value))&&(!estadoFiltro.value||p.estado===estadoFiltro.value)));
watch([empresaFiltro,estadoFiltro],()=>{if(!periodosFiltrados.value.some(p=>String(p.id)===String(periodoId.value)))periodoId.value=periodosFiltrados.value[0]?.id||''});
watch(periodoId,id=>{if(id&&String(id)!==String(props.periodoSeleccionado?.id))router.get(route('ventas-externas.index'),{periodo_id:id},{preserveState:true,preserveScroll:true,replace:true})});
const money=v=>'S/ '+Number(v||0).toLocaleString('es-PE',{minimumFractionDigits:2});
const totalP=computed(()=>props.periodoSeleccionado?.pagos.reduce((s,p)=>s+Number(p.total),0)||0);
const fijoP=computed(()=>props.periodoSeleccionado?.pagos.reduce((s,p)=>s+Number(p.pago_fijo),0)||0);
const comisionP=computed(()=>props.periodoSeleccionado?.pagos.reduce((s,p)=>s+Number(p.comision),0)||0);
const modalG=ref(false),modalP=ref(false),detalle=ref(null),actual=ref(null);
const gf=useForm({empresa_id:null,anio:hoy.getFullYear(),mes:hoy.getMonth()+1,fecha_pago:''});
function abrirGenerar(){gf.reset();gf.anio=hoy.getFullYear();gf.mes=hoy.getMonth()+1;modalG.value=true} function generar(){gf.post(route('ventas-externas.generar'))}
const pf=useForm({pago_fijo:0,ventas:0,tipo_comision:'porcentaje',porcentaje_comision:0,comision:0,bonos:0,adelantos:0,observacion:''});
function editar(p){actual.value=p;pf.defaults({pago_fijo:p.pago_fijo,ventas:p.ventas,tipo_comision:p.tipo_comision,porcentaje_comision:p.porcentaje_comision,comision:p.comision,bonos:p.bonos,adelantos:p.adelantos,observacion:p.observacion||''});pf.reset();modalP.value=true}
const comision=computed(()=>pf.tipo_comision==='porcentaje'?Number(pf.ventas||0)*Number(pf.porcentaje_comision||0)/100:Number(pf.comision||0)); const total=computed(()=>Math.max(0,Number(pf.pago_fijo||0)+comision.value+Number(pf.bonos||0)-Number(pf.adelantos||0)));
function guardar(){pf.put(route('ventas-externas.pagos.update',actual.value.id),{preserveScroll:true,onSuccess:()=>modalP.value=false})}
const inp='mt-1 block w-full rounded-md border-gray-300 text-sm shadow-sm';
</script>
<template><Head title="Ventas externos"/><AuthenticatedLayout><template #header><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-semibold">Ventas externos</h2><p class="text-xs text-gray-500">Consulta, registra y cierra pagos en una sola pantalla</p></div><div class="flex gap-2"><Link :href="route('ventas-externas.vendedores')" class="rounded-md border border-indigo-200 px-4 py-2 text-sm font-semibold text-indigo-700">👤 Vendedores</Link><button @click="abrirGenerar" class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">+ Generar periodo</button></div></div></template>
<div class="space-y-5 p-5">
<div v-if="periodoSeleccionado" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-xl border border-gray-100 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Vendedores activos</p><p class="mt-2 text-3xl font-bold text-emerald-600">{{periodoSeleccionado.pagos.length}}</p></div><div class="rounded-xl border border-gray-100 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Pago fijo</p><p class="mt-2 text-2xl font-bold text-blue-700">{{money(fijoP)}}</p></div><div class="rounded-xl border border-gray-100 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Comisiones</p><p class="mt-2 text-2xl font-bold text-orange-600">{{money(comisionP)}}</p></div><div class="rounded-xl border border-gray-100 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Total a pagar</p><p class="mt-2 text-2xl font-bold text-indigo-700">{{money(totalP)}}</p></div></div>
<div class="rounded-lg border border-blue-200 bg-blue-50 px-5 py-3.5 text-sm text-blue-800"><b>Módulo independiente:</b> selecciona los filtros, registra los importes y cierra el periodo cuando todo esté conforme.</div>
<section class="rounded-xl border border-gray-100 bg-white p-5 shadow-sm"><div class="filtros-grid"><div><label class="text-xs font-semibold uppercase tracking-wide text-gray-500">Periodo</label><select v-model="periodoId" :class="inp"><option value="">Sin periodos</option><option v-for="p in periodosFiltrados" :key="p.id" :value="p.id">{{meses[p.mes]}} {{p.anio}}</option></select></div><div><label class="text-xs font-semibold uppercase tracking-wide text-gray-500">Empresa pagadora</label><select v-model="empresaFiltro" :class="inp"><option value="">Todas las empresas configuradas</option><option v-for="e in empresas" :key="e.id" :value="e.id">{{e.nombre_comercial||e.razon_social}}</option></select></div><div><label class="text-xs font-semibold uppercase tracking-wide text-gray-500">Estado</label><select v-model="estadoFiltro" :class="inp"><option value="">Todos</option><option value="abierto">Abiertos</option><option value="cerrado">Cerrados</option></select></div></div></section>
<template v-if="periodoSeleccionado">
<section class="overflow-x-auto rounded-xl bg-white shadow-sm"><div class="flex flex-wrap items-center justify-between gap-2 border-b px-5 py-4"><div><h3 class="font-semibold">{{meses[periodoSeleccionado.mes]}} {{periodoSeleccionado.anio}}</h3><p class="text-xs text-gray-500">{{periodoSeleccionado.estado==='abierto'?'Pendiente de revisión y cierre':'Periodo cerrado'}}</p></div><div class="flex gap-2"><a :href="route('ventas-externas.export',periodoSeleccionado.id)" class="rounded-md border border-emerald-500 px-3 py-2 text-xs font-semibold text-emerald-700">📥 Exportar</a><button v-if="periodoSeleccionado.estado==='abierto'" @click="router.post(route('ventas-externas.cerrar',periodoSeleccionado.id),{},{preserveScroll:true})" class="rounded-md border border-indigo-500 px-3 py-2 text-xs font-semibold text-indigo-700">🔒 Cerrar periodo</button><button v-else @click="router.post(route('ventas-externas.reabrir',periodoSeleccionado.id),{},{preserveScroll:true})" class="rounded-md bg-gray-100 px-3 py-2 text-xs font-semibold">Reabrir</button></div></div>
<table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Vendedor</th><th class="px-4 py-3">DNI/RUC</th><th class="px-4 py-3 text-right">Pago fijo</th><th class="px-4 py-3 text-right">Ventas</th><th class="px-4 py-3 text-right">Comisión</th><th class="px-4 py-3 text-right">Bonos</th><th class="px-4 py-3 text-right">Adelantos</th><th class="px-4 py-3 text-right">Total</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y"><tr v-for="p in periodoSeleccionado.pagos" :key="p.id"><td class="px-4 py-4 font-semibold">{{p.vendedor}}</td><td class="px-4 py-4">{{p.documento}}</td><td class="px-4 py-4 text-right">{{money(p.pago_fijo)}}</td><td class="px-4 py-4 text-right">{{money(p.ventas)}}</td><td class="px-4 py-4 text-right text-orange-600">{{money(p.comision)}}</td><td class="px-4 py-4 text-right">{{money(p.bonos)}}</td><td class="px-4 py-4 text-right text-red-600">{{money(p.adelantos)}}</td><td class="px-4 py-4 text-right font-bold text-emerald-700">{{money(p.total)}}</td><td class="whitespace-nowrap px-4 py-4 text-right"><button @click="detalle=p" class="mr-2 rounded bg-gray-100 px-3 py-1.5 text-xs font-semibold">Ver</button><button v-if="periodoSeleccionado.estado==='abierto'" @click="editar(p)" class="rounded bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700">Editar</button></td></tr></tbody></table></section></template>
<div v-else class="rounded-xl bg-white p-10 text-center text-gray-500 shadow-sm">No existe un periodo para los filtros seleccionados.</div></div>
<CrudModal :show="modalG" titulo="Generar periodo" @close="modalG=false"><form @submit.prevent="generar" class="grid gap-4 md:grid-cols-2"><div class="md:col-span-2"><label class="text-sm">Empresa pagadora</label><select v-model="gf.empresa_id" :class="inp"><option :value="null">Selecciona</option><option v-for="e in empresas" :key="e.id" :value="e.id">{{e.nombre_comercial||e.razon_social}}</option></select></div><div><label class="text-sm">Mes</label><select v-model="gf.mes" :class="inp"><option v-for="m in 12" :key="m" :value="m">{{meses[m]}}</option></select></div><div><label class="text-sm">Año</label><input v-model="gf.anio" type="number" :class="inp"/></div><div><label class="text-sm">Fecha de pago</label><input v-model="gf.fecha_pago" type="date" :class="inp"/></div><div class="flex justify-end gap-2 md:col-span-2"><button type="button" @click="modalG=false" class="rounded bg-gray-100 px-4 py-2">Cancelar</button><button class="rounded bg-indigo-600 px-4 py-2 font-semibold text-white">Generar y mostrar</button></div></form></CrudModal>
<CrudModal :show="!!detalle" titulo="Detalle del cálculo" @close="detalle=null"><div v-if="detalle" class="space-y-3"><b>{{detalle.vendedor}}</b><div class="rounded-lg bg-gray-50 p-4 text-sm"><div class="flex justify-between py-1"><span>Pago fijo</span><b>{{money(detalle.pago_fijo)}}</b></div><div class="flex justify-between py-1"><span>Ventas registradas</span><span>{{money(detalle.ventas)}}</span></div><div class="flex justify-between py-1 text-orange-600"><span>+ Comisión {{detalle.tipo_comision==='porcentaje'?'('+detalle.porcentaje_comision+'%)':'manual'}}</span><b>{{money(detalle.comision)}}</b></div><div class="flex justify-between py-1"><span>+ Bonos</span><b>{{money(detalle.bonos)}}</b></div><div class="flex justify-between py-1 text-red-600"><span>− Adelantos</span><b>{{money(detalle.adelantos)}}</b></div><div class="mt-2 flex justify-between border-t pt-3 text-lg"><b>Total</b><b class="text-emerald-700">{{money(detalle.total)}}</b></div></div><div class="text-right"><button @click="detalle=null" class="rounded bg-indigo-600 px-4 py-2 text-white">Cerrar</button></div></div></CrudModal>
<CrudModal :show="modalP" titulo="Registrar datos del vendedor" @close="modalP=false"><form @submit.prevent="guardar" class="grid gap-4 md:grid-cols-2"><div class="md:col-span-2"><b>{{actual?.vendedor}}</b><p class="text-xs text-gray-500">El total se recalcula automáticamente.</p></div><div><label class="text-sm">Pago fijo</label><input v-model="pf.pago_fijo" type="number" step=".01" :class="inp"/></div><div><label class="text-sm">Ventas realizadas</label><input v-model="pf.ventas" type="number" step=".01" :class="inp"/></div><div><label class="text-sm">Tipo de comisión</label><select v-model="pf.tipo_comision" :class="inp"><option value="porcentaje">Porcentaje</option><option value="manual">Manual</option></select></div><div v-if="pf.tipo_comision==='porcentaje'"><label class="text-sm">Porcentaje</label><input v-model="pf.porcentaje_comision" type="number" step=".01" :class="inp"/></div><div v-else><label class="text-sm">Comisión manual</label><input v-model="pf.comision" type="number" step=".01" :class="inp"/></div><div><label class="text-sm">Bonos</label><input v-model="pf.bonos" type="number" step=".01" :class="inp"/></div><div><label class="text-sm">Adelantos</label><input v-model="pf.adelantos" type="number" step=".01" :class="inp"/></div><div class="md:col-span-2"><label class="text-sm">Observación</label><textarea v-model="pf.observacion" :class="inp"></textarea></div><div class="md:col-span-2 rounded-lg bg-emerald-50 p-4"><div class="flex justify-between"><span>Comisión</span><b>{{money(comision)}}</b></div><div class="mt-2 flex justify-between border-t pt-2 text-lg"><b>Total</b><b class="text-emerald-700">{{money(total)}}</b></div></div><div class="flex justify-end gap-2 md:col-span-2"><button type="button" @click="modalP=false" class="rounded bg-gray-100 px-4 py-2">Cancelar</button><button class="rounded bg-emerald-600 px-4 py-2 font-semibold text-white">Guardar</button></div></form></CrudModal>
</AuthenticatedLayout></template>
<style scoped>
.filtros-grid { display: grid; grid-template-columns: 1fr; gap: 1rem; align-items: end; }
@media (min-width: 768px) { .filtros-grid { grid-template-columns: minmax(190px, 0.8fr) minmax(360px, 1.8fr) minmax(180px, 0.7fr); } }
</style>
