<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'; import CrudModal from '@/Components/CrudModal.vue';
import {Head,Link,router,useForm} from '@inertiajs/vue3'; import {computed,ref} from 'vue';
const props=defineProps({periodo:Object}); const meses=['','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const modal=ref(false),actual=ref(null),detalle=ref(null); const f=useForm({pago_fijo:0,ventas:0,tipo_comision:'porcentaje',porcentaje_comision:0,comision:0,bonos:0,adelantos:0,observacion:''});
const money=v=>'S/ '+Number(v||0).toLocaleString('es-PE',{minimumFractionDigits:2}); const inp='mt-1 block w-full rounded-md border-gray-300 text-sm shadow-sm';
const comision=computed(()=>f.tipo_comision==='porcentaje'?Number(f.ventas||0)*Number(f.porcentaje_comision||0)/100:Number(f.comision||0)); const total=computed(()=>Math.max(0,Number(f.pago_fijo||0)+comision.value+Number(f.bonos||0)-Number(f.adelantos||0)));
const totalP=computed(()=>props.periodo.pagos.reduce((s,p)=>s+Number(p.total),0)); const fijoP=computed(()=>props.periodo.pagos.reduce((s,p)=>s+Number(p.pago_fijo),0)); const comP=computed(()=>props.periodo.pagos.reduce((s,p)=>s+Number(p.comision),0));
function editar(p){actual.value=p;f.defaults({pago_fijo:p.pago_fijo,ventas:p.ventas,tipo_comision:p.tipo_comision,porcentaje_comision:p.porcentaje_comision,comision:p.comision,bonos:p.bonos,adelantos:p.adelantos,observacion:p.observacion||''});f.reset();modal.value=true}
function guardar(){f.put(route('ventas-externas.pagos.update',actual.value.id),{onSuccess:()=>modal.value=false})}
</script>
<template><Head title="Detalle de ventas externas"/><AuthenticatedLayout><template #header><div class="flex flex-wrap items-center justify-between gap-3"><div><Link :href="route('ventas-externas.index')" class="text-xs text-indigo-600">← Periodos de ventas externas</Link><h2 class="text-xl font-semibold">{{meses[periodo.mes]}} {{periodo.anio}}</h2><p class="text-xs text-gray-500">Empresa pagadora: {{periodo.empresa}}</p></div><div class="flex gap-2"><a :href="route('ventas-externas.export',periodo.id)" class="rounded-md border border-emerald-500 px-4 py-2 text-sm font-semibold text-emerald-700">📥 Exportar</a><button v-if="periodo.estado==='abierto'" @click="router.post(route('ventas-externas.cerrar',periodo.id))" class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">🔒 Cerrar periodo</button><button v-else @click="router.post(route('ventas-externas.reabrir',periodo.id))" class="rounded-md bg-gray-200 px-4 py-2 text-sm font-semibold">Reabrir</button></div></div></template>
<div class="space-y-5 p-5"><div class="grid gap-4 md:grid-cols-4"><div class="rounded-xl bg-white p-4 shadow-sm"><p class="text-xs uppercase text-gray-500">Vendedores</p><p class="mt-1 text-2xl font-bold">{{periodo.pagos.length}}</p></div><div class="rounded-xl bg-white p-4 shadow-sm"><p class="text-xs uppercase text-gray-500">Pagos fijos</p><p class="mt-1 text-xl font-bold text-blue-700">{{money(fijoP)}}</p></div><div class="rounded-xl bg-white p-4 shadow-sm"><p class="text-xs uppercase text-gray-500">Comisiones</p><p class="mt-1 text-xl font-bold text-orange-600">{{money(comP)}}</p></div><div class="rounded-xl bg-white p-4 shadow-sm"><p class="text-xs uppercase text-gray-500">Total a pagar</p><p class="mt-1 text-xl font-bold text-emerald-700">{{money(totalP)}}</p></div></div>
<section class="rounded-xl bg-white shadow-sm"><div class="border-b px-5 py-4"><h3 class="font-semibold">Pagos de vendedores</h3><p class="text-xs text-gray-500">La tabla muestra solamente el resultado. Usa “Ver cálculo” para revisar el detalle.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Vendedor</th><th class="px-5 py-3 text-right">Ventas registradas</th><th class="px-5 py-3 text-right">Comisión calculada</th><th class="px-5 py-3 text-right">Descuentos</th><th class="px-5 py-3 text-right">Total a pagar</th><th class="px-5 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y"><tr v-for="p in periodo.pagos" :key="p.id"><td class="px-5 py-4"><b>{{p.vendedor}}</b><div class="text-xs text-gray-400">{{p.documento}}</div></td><td class="px-5 py-4 text-right">{{money(p.ventas)}}</td><td class="px-5 py-4 text-right text-orange-600">{{money(p.comision)}}</td><td class="px-5 py-4 text-right text-red-600">{{money(p.adelantos)}}</td><td class="px-5 py-4 text-right text-lg font-bold text-emerald-700">{{money(p.total)}}</td><td class="px-5 py-4 text-right"><button @click="detalle=p" class="mr-2 rounded-md bg-gray-100 px-3 py-2 text-xs font-semibold">Ver cálculo</button><button v-if="periodo.estado==='abierto'" @click="editar(p)" class="rounded-md bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700">Registrar datos</button></td></tr></tbody></table></div></section></div>
<CrudModal :show="!!detalle" titulo="Detalle del cálculo" @close="detalle=null"><div v-if="detalle" class="space-y-3"><div><b>{{detalle.vendedor}}</b><p class="text-xs text-gray-500">{{detalle.documento}}</p></div><div class="rounded-lg bg-gray-50 p-4 text-sm"><div class="flex justify-between py-1"><span>Pago fijo</span><b>{{money(detalle.pago_fijo)}}</b></div><div class="flex justify-between py-1"><span>Ventas registradas</span><span>{{money(detalle.ventas)}}</span></div><div class="flex justify-between py-1 text-orange-700"><span>+ Comisión {{detalle.tipo_comision==='porcentaje'?'('+detalle.porcentaje_comision+'%)':'manual'}}</span><b>{{money(detalle.comision)}}</b></div><div class="flex justify-between py-1 text-emerald-700"><span>+ Bonos</span><b>{{money(detalle.bonos)}}</b></div><div class="flex justify-between py-1 text-red-600"><span>− Adelantos</span><b>{{money(detalle.adelantos)}}</b></div><div class="mt-2 flex justify-between border-t pt-3 text-lg"><b>Total a pagar</b><b class="text-emerald-700">{{money(detalle.total)}}</b></div></div><p v-if="detalle.observacion" class="rounded bg-amber-50 p-3 text-sm">{{detalle.observacion}}</p><div class="text-right"><button @click="detalle=null" class="rounded-md bg-indigo-600 px-4 py-2 font-semibold text-white">Entendido</button></div></div></CrudModal>
<CrudModal :show="modal" titulo="Registrar datos del periodo" @close="modal=false"><form @submit.prevent="guardar" class="grid gap-4 md:grid-cols-2"><div class="md:col-span-2"><b>{{actual?.vendedor}}</b><p class="text-xs text-gray-500">Ingresa ventas, bonos o adelantos. El sistema calcula el resultado.</p></div><div><label class="text-sm">Pago fijo</label><input v-model="f.pago_fijo" type="number" step=".01" :class="inp"/></div><div><label class="text-sm">Ventas realizadas</label><input v-model="f.ventas" type="number" step=".01" :class="inp"/></div><div><label class="text-sm">Comisión</label><select v-model="f.tipo_comision" :class="inp"><option value="porcentaje">Porcentaje automático</option><option value="manual">Monto manual</option></select></div><div v-if="f.tipo_comision==='porcentaje'"><label class="text-sm">Porcentaje</label><input v-model="f.porcentaje_comision" type="number" step=".01" :class="inp"/></div><div v-else><label class="text-sm">Monto de comisión</label><input v-model="f.comision" type="number" step=".01" :class="inp"/></div><div><label class="text-sm">Bonos</label><input v-model="f.bonos" type="number" step=".01" :class="inp"/></div><div><label class="text-sm">Adelantos a descontar</label><input v-model="f.adelantos" type="number" step=".01" :class="inp"/></div><div class="md:col-span-2"><label class="text-sm">Observación</label><textarea v-model="f.observacion" :class="inp"></textarea></div><div class="md:col-span-2 rounded-lg bg-emerald-50 p-4"><div class="flex justify-between text-sm"><span>Comisión</span><b>{{money(comision)}}</b></div><div class="mt-2 flex justify-between border-t border-emerald-200 pt-2 text-lg"><b>Total a pagar</b><b class="text-emerald-700">{{money(total)}}</b></div></div><div class="flex justify-end gap-2 md:col-span-2"><button type="button" @click="modal=false" class="rounded bg-gray-100 px-4 py-2">Cancelar</button><button class="rounded bg-emerald-600 px-4 py-2 font-semibold text-white">Guardar y calcular</button></div></form></CrudModal>
</AuthenticatedLayout></template>
