<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import CrudModal from '@/Components/CrudModal.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
defineProps({ vendedores: Array, empresas: Array });
const actual=ref(null), modalV=ref(false), modalT=ref(false), buscandoDni=ref(false), msgDni=ref('');
const vf=useForm({tipo_documento:'DNI',numero_documento:'',nombre:'',telefono:'',correo:'',activo:true});
const tf=useForm({empresa_id:null,tipo_pago:'mixto',pago_fijo:0,tipo_comision:'porcentaje',porcentaje_comision:0});
const inp='mt-1 block w-full rounded-md border-gray-300 text-sm shadow-sm';
const money=v=>'S/ '+Number(v||0).toLocaleString('es-PE',{minimumFractionDigits:2});
const tipo=v=>({fijo:'Solo pago fijo',comision:'Solo comisión',mixto:'Fijo + comisión'}[v]);
function nuevo(){actual.value=null;vf.reset();vf.tipo_documento='DNI';vf.activo=true;msgDni.value='';modalV.value=true}
function editar(v){actual.value=v;vf.defaults({tipo_documento:v.tipo_documento,numero_documento:v.numero_documento,nombre:v.nombre,telefono:v.telefono||'',correo:v.correo||'',activo:v.activo});vf.reset();msgDni.value='';modalV.value=true}
function guardar(){const o={onSuccess:()=>modalV.value=false};actual.value?vf.put(route('ventas-externas.vendedores.update',actual.value.id),o):vf.post(route('ventas-externas.vendedores.store'),o)}
function tarifa(v,t=null){actual.value=v;tf.defaults({empresa_id:t?.empresa_id??null,tipo_pago:t?.tipo_pago??'mixto',pago_fijo:t?.pago_fijo??0,tipo_comision:t?.tipo_comision??'porcentaje',porcentaje_comision:t?.porcentaje_comision??0});tf.reset();modalT.value=true}
function guardarTarifa(){tf.post(route('ventas-externas.tarifas.store',actual.value.id),{onSuccess:()=>modalT.value=false})}
async function buscarDni(){msgDni.value='';const dni=String(vf.numero_documento||'').trim();if(!/^\d{8}$/.test(dni)){msgDni.value='Escribe un DNI válido de 8 dígitos.';return}buscandoDni.value=true;try{const r=await fetch(route('ventas-externas.consulta-dni',dni),{headers:{Accept:'application/json'}});const j=await r.json();if(j.ok){vf.nombre=[j.apellido_paterno,j.apellido_materno,j.nombres].filter(Boolean).join(' ');msgDni.value='✓ Datos oficiales encontrados en RENIEC.'}else msgDni.value=j.mensaje||'DNI no encontrado.'}catch{msgDni.value='No se pudo consultar RENIEC.'}finally{buscandoDni.value=false}}
</script>
<template><Head title="Vendedores externos"/><AuthenticatedLayout>
<template #header><div class="flex items-center justify-between"><div><Link :href="route('ventas-externas.index')" class="text-xs text-indigo-600">← Ventas externos</Link><h2 class="text-xl font-semibold">Vendedores externos</h2></div><button @click="nuevo" class="rounded-md bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">+ Nuevo vendedor</button></div></template>
<div class="space-y-4 p-5"><div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><b>Registro ordenado por fila.</b> Cada fila representa la condición del vendedor con una empresa pagadora.</div>
<div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Vendedor</th><th class="px-4 py-3">Documento</th><th class="px-4 py-3">Empresa pagadora</th><th class="px-4 py-3">Forma de pago</th><th class="px-4 py-3 text-right">Condición</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y">
<template v-for="v in vendedores" :key="v.id"><tr v-for="(t,i) in v.tarifas" :key="t.id" class="hover:bg-gray-50"><td class="px-4 py-4"><b v-if="i===0">{{v.nombre}}</b><div v-if="i===0" class="text-xs text-gray-400">{{v.telefono||'Sin teléfono'}}</div></td><td class="px-4 py-4">{{i===0?v.tipo_documento+' '+v.numero_documento:''}}</td><td class="px-4 py-4 font-medium">{{t.empresa}}</td><td class="px-4 py-4">{{tipo(t.tipo_pago)}}</td><td class="px-4 py-4 text-right"><b v-if="t.tipo_pago!=='comision'" class="text-blue-700">{{money(t.pago_fijo)}} fijo</b><span v-if="t.tipo_pago==='mixto'"> + </span><b v-if="t.tipo_pago!=='fijo'" class="text-orange-600">{{t.tipo_comision==='porcentaje'?t.porcentaje_comision+'%':'Manual'}}</b></td><td class="px-4 py-4 text-right"><button @click="tarifa(v,t)" class="mr-2 rounded bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700">Editar condición</button><button v-if="i===0" @click="editar(v)" class="rounded bg-gray-100 px-3 py-1.5 text-xs font-semibold">Editar vendedor</button></td></tr>
<tr v-if="!v.tarifas.length"><td class="px-4 py-4 font-semibold">{{v.nombre}}</td><td class="px-4 py-4">{{v.tipo_documento}} {{v.numero_documento}}</td><td colspan="3" class="px-4 py-4 text-gray-400">Sin empresa ni condición configurada</td><td class="px-4 py-4 text-right"><button @click="tarifa(v)" class="mr-2 rounded bg-indigo-600 px-3 py-1.5 text-xs font-semibold text-white">Configurar pago</button><button @click="editar(v)" class="rounded bg-gray-100 px-3 py-1.5 text-xs font-semibold">Editar vendedor</button></td></tr></template>
<tr v-if="!vendedores.length"><td colspan="6" class="px-4 py-10 text-center text-gray-500">No hay vendedores registrados.</td></tr></tbody></table></div></div>
<CrudModal :show="modalV" :titulo="actual?'Editar vendedor':'Nuevo vendedor'" @close="modalV=false"><form @submit.prevent="guardar" class="grid gap-4 md:grid-cols-2"><div><label class="text-sm">Documento</label><div class="flex items-end gap-2"><select v-model="vf.tipo_documento" :class="inp"><option>DNI</option><option>RUC</option><option>CE</option></select><input v-model="vf.numero_documento" :class="inp" placeholder="Número"/><button v-if="vf.tipo_documento==='DNI'" type="button" @click="buscarDni" :disabled="buscandoDni" class="mb-0.5 whitespace-nowrap rounded-md bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700">{{buscandoDni?'Buscando…':'🔍 RENIEC'}}</button></div><p v-if="msgDni" class="mt-1 text-xs text-indigo-600">{{msgDni}}</p></div><div><label class="text-sm">Nombre completo</label><input v-model="vf.nombre" :class="inp"/></div><div><label class="text-sm">Teléfono</label><input v-model="vf.telefono" :class="inp"/></div><div><label class="text-sm">Correo</label><input v-model="vf.correo" :class="inp"/></div><label v-if="actual" class="flex gap-2"><input v-model="vf.activo" type="checkbox"/>Activo</label><div class="flex justify-end gap-2 md:col-span-2"><button type="button" @click="modalV=false" class="rounded bg-gray-100 px-4 py-2">Cancelar</button><button class="rounded bg-emerald-600 px-4 py-2 font-semibold text-white">Guardar</button></div></form></CrudModal>
<CrudModal :show="modalT" titulo="Condición de pago por empresa" @close="modalT=false"><form @submit.prevent="guardarTarifa" class="grid gap-4 md:grid-cols-2"><div class="md:col-span-2"><b>{{actual?.nombre}}</b><p class="text-xs text-gray-500">Esta condición se aplicará solamente cuando pague la empresa seleccionada.</p></div><div class="md:col-span-2"><label class="text-sm">Empresa pagadora</label><select v-model="tf.empresa_id" :class="inp"><option :value="null">Selecciona</option><option v-for="e in empresas" :key="e.id" :value="e.id">{{e.nombre_comercial||e.razon_social}}</option></select></div><div><label class="text-sm">Forma de pago</label><select v-model="tf.tipo_pago" :class="inp"><option value="fijo">Solo pago fijo</option><option value="comision">Solo comisión</option><option value="mixto">Pago fijo + comisión</option></select></div><div v-if="tf.tipo_pago!=='comision'"><label class="text-sm">Pago fijo</label><input v-model="tf.pago_fijo" type="number" step=".01" :class="inp"/></div><div v-if="tf.tipo_pago!=='fijo'"><label class="text-sm">Cómo calcular comisión</label><select v-model="tf.tipo_comision" :class="inp"><option value="porcentaje">Porcentaje de ventas</option><option value="manual">Monto manual cada mes</option></select></div><div v-if="tf.tipo_pago!=='fijo'&&tf.tipo_comision==='porcentaje'"><label class="text-sm">Porcentaje</label><input v-model="tf.porcentaje_comision" type="number" step=".01" :class="inp"/></div><div class="flex justify-end gap-2 md:col-span-2"><button type="button" @click="modalT=false" class="rounded bg-gray-100 px-4 py-2">Cancelar</button><button class="rounded bg-indigo-600 px-4 py-2 font-semibold text-white">Guardar condición</button></div></form></CrudModal>
</AuthenticatedLayout></template>
